config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about",to: "pages#about"
  resources :articles
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article <ApplicationRecord
    validates :title, presence: true, length: {minimum:5, maximum:100}
    validates :description, presence: true, length: {minimum:7, maximum:200}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   before_action :set_article, only: [:show, :edit, :update, :destroy]
   def show 
   
   end 
   def index
      @articles=Article.all
   end
   def new
      @article=Article.new
   end
   def destroy 
  
      @article.destroy
      flash[:notice] = "The article is deleted"
      redirect_to articles_path(@article)
   end
   def update
     
      if @article.update(article_params)
         flash[:notice] = "The article is successfully updated"
         redirect_to articles_path(@articles)
      else
         render "edit"
      end


      
   end
   def edit 
      
   end
   def create
      @article=Article.new(article_params)
      if @article.save
         flash[:notice] = "Article was created successfully"
         redirect_to articles_path(@article)
      else
         render "new"
      end
   end
   private
   def set_article
      @article=Article.find(params[:id])
   end
   def article_params
      params.require(:article).permit(:title, :description)
   end



   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <% @article.errors.full_messages.each do |msg| %>
        <ul><li><%=msg%> </li></ul>
       
    <%end%>
<%end%>
 <%= form_with(model:@article, local:true)  do |f|%>
 <p>
 <%=f.label :title %>
 <%=f.text_field :title%>
 </p>
 <br>
 <p>
 <%=f.label :description %>
 <%=f.text_area :description%>
 </p>
 <p>
 <%=f.submit%>
 </p>
 <%end%>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= render "form" %>
 <%= link_to "Return to main", articles_path %>

app/views/articles/index.html.erb
<h1>this is index page</h1>
<br>
<table>
<%if @articles.length>0%>
   <tr>
    <th>Title</th>
    <th>Description</th>
    <th colspan=3>Action</th>
  </tr>
  <%else%>
  <h3>no data availabe</h3>
  <%end%>

 
  <tbody>
  <%  @articles.each do |article|%>
  <tr>
  <td><%=article.title%></td>
  <td><%=article.description%></td>
  <td><%= link_to "Show",article_path(article.id) %>
   <td><%= link_to "Edit",edit_article_path(article.id) %>
  <td><%= link_to "Delete", article_path(article.id), method: :delete, data: {confirm: "are you sure?"} %></td>
  </tr>
  <%end%>

  </tbody>
</table>
<br>
<%=link_to "Create Article", new_article_path %>

app/views/articles/new.html.erb
<h1>this is a new article</h1>
<%= render "form" %>
 <%= link_to "Return to main", articles_path %>

app/views/articles/show.html.erb
<h1>showing articles details</h1>
<h3>title:<%=@article.title %></h3>
<h3>Description:<%=@article.description %></h3>
<%=link_to "edit Article", edit_article_path(@article.id) %> |
<%= link_to "Delete Article", article_path(@article.id), method: :delete,  data: {confirm: "are you sure?"}%> |
<%= link_to "Return to main", articles_path %>

app/views/layouts/_messages.html.erb
  <% flash.each do |name,msg| %>
    <%=msg%>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlogProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/messages" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>this is about page</h1>
<br>
<%= link_to "Return to article list", articles_path %> |
<%= link_to "Home", root_path %> 

app/views/pages/home.html.erb
<h1>Wellcome to the Alpha Article Project</h1>
<br>
<%= link_to "Artilce List", articles_path %> |
<%= link_to "Create Article", new_article_path%> |
<%= link_to "About Us", about_path%>